# --------------------------------------------------------------------------------------------------
# 1. 此smartdns配置文件用于fancyss DNS分流解析，配置文件为：5：自定义配置2
# 2. 域名解析请求将被同时发往所有上游DNS服务器，国内DNS服务器只接受解析到国内的ip，国外的都接受。
# 3. smartdns相关文档请参考：https://github.com/pymumu/smartdns#smartdns
# --------------------------------------------------------------------------------------------------

# 监听端口：7913，请勿更改
bind [::]:7913

# 日志记录
log-level info
log-file /tmp/smartdns_log.txt
log-size 2M
log-num 1

# 审计
audit-enable yes
audit-file /tmp/smartdns_audit.txt
audit-size 2M
audit-num 1

# chnroute，用于default组解析结果过滤
conf-file /tmp/whitelist_ip.txt

# define proxy server
proxy-server socks5://127.0.0.1:23456 -name fancy_proxy

# default server
server 117.50.10.10 -whitelist-ip
server 117.50.60.30 -whitelist-ip
server 223.5.5.5 -whitelist-ip
server 119.29.29.29 -whitelist-ip
server 114.114.114.114 -whitelist-ip
server 180.184.1.1 -whitelist-ip
server 1.2.4.8 -whitelist-ip
server 180.76.76.76 -whitelist-ip
server-tcp 8.8.8.8 -proxy fancy_proxy
server-tcp 1.1.1.1 -proxy fancy_proxy
